SITE_ID = 1

DEBUG = True

SOCIALACCOUNT_PROVIDERS = {
    'evernote': {
        'EVERNOTE_HOSTNAME': 'sandbox.evernote.com'
    }
}

EVERNOTE_IS_SANDBOX = True

AWS_SECRET_ACCESS_KEY = 'YOUR-SECRET-ACCESS-KEY'
